let DB={};const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
async function load(){let files=["class","students","schedule","duty","tasks","cash","announcements"];try{let data=await Promise.all(files.map(x=>fetch("data/"+x+".json").then(r=>r.json())));files.forEach((x,i)=>DB[x]=data[i]);applyClass();renderAll();setTimeout(()=>$("#loader").classList.add("hidden"),350)}catch(e){$("#loader").innerHTML="<b>Gagal memuat database JSON.</b><small>Pastikan folder data ikut di-upload ke Vercel.</small>"}}
function applyClass(){let c=DB.class;document.title=c.appName;$("#appName").textContent=c.appName;$("#schoolName").textContent=c.schoolName;$("#className").textContent=c.className;$("#teacher").textContent=c.homeroomTeacher;$("#year").textContent=c.schoolYear;$("#dTeacher").textContent=c.homeroomTeacher;$("#dLeader").textContent=c.classLeader;$("#dYear").textContent=c.schoolYear;$("#welcome").textContent=`Kelola ${c.className} dengan cara yang lebih modern.`}
const titles={dashboard:"Dashboard",students:"Data Siswa",schedule:"Jadwal Pelajaran",duty:"Jadwal Piket",tasks:"Tugas Kelas",cash:"Kas Kelas",news:"Pengumuman"};
function showPage(id){$$(".page").forEach(x=>x.classList.toggle("active",x.id===id));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));$("#title").textContent=titles[id];if(innerWidth<1001)$("aside").classList.remove("open");scrollTo({top:0,behavior:"smooth"})}
$$(".nav").forEach(x=>x.onclick=()=>showPage(x.dataset.page));$("#menu").onclick=()=>$("aside").classList.toggle("open");$("#theme").onclick=()=>document.body.classList.toggle("light");
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function rupiah(n){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n)}
function renderStudents(q=""){let a=DB.students.filter(s=>(s.name+" "+s.nis).toLowerCase().includes(q.toLowerCase()));$("#studentGrid").innerHTML=a.map(s=>`<article class="student"><div class="avatar">${esc(s.name.split(" ").map(x=>x[0]).slice(0,2).join(""))}</div><h3>${esc(s.name)}</h3><small>NIS ${esc(s.nis)} • ${s.gender==="L"?"Laki-laki":"Perempuan"}</small></article>`).join("");$("#sCount").textContent=DB.students.length}
function renderSchedule(){$("#scheduleRows").innerHTML=DB.schedule.map(s=>`<tr><td>${s.day}</td><td>${s.time}</td><td><b>${esc(s.subject)}</b></td><td>${esc(s.teacher)}</td></tr>`).join("");$("#dashSchedule").innerHTML=DB.schedule.slice(0,3).map(s=>`<div class="info"><div><b>${esc(s.subject)}</b><small>${s.day} • ${s.time} • ${esc(s.teacher)}</small></div></div>`).join("")}
function renderDuty(){$("#dutyGrid").innerHTML=Object.entries(DB.duty).map(([d,p])=>`<div class="duty-card"><h3>${d}</h3>${p.map(x=>`<div class="person">👤 ${esc(x)}</div>`).join("")}</div>`).join("")}
function renderTasks(){$("#taskList").innerHTML=DB.tasks.map(t=>`<div class="task ${t.done?"done":""}"><input type="checkbox" ${t.done?"checked":""} onchange="toggleTask(${t.id})"><div class="grow"><b>${esc(t.name)}</b><small>${esc(t.subject)} • Deadline: ${esc(t.due)}</small></div></div>`).join("");$("#tCount").textContent=DB.tasks.filter(x=>!x.done).length}
function toggleTask(id){let t=DB.tasks.find(x=>x.id===id);t.done=!t.done;renderTasks();toast(t.done?"Tugas selesai ✓":"Tugas dibuka kembali")}
function renderCash(){let i=DB.cash.filter(x=>x.type==="income").reduce((a,x)=>a+x.amount,0),o=DB.cash.filter(x=>x.type==="expense").reduce((a,x)=>a+x.amount,0);$("#income").textContent=rupiah(i);$("#expense").textContent=rupiah(o);$("#balance").textContent=rupiah(i-o);$("#cCount").textContent=rupiah(i-o);$("#cashRows").innerHTML=DB.cash.map(x=>`<tr><td>${x.date}</td><td>${esc(x.description)}</td><td><span class="badge ${x.type}">${x.type==="income"?"PEMASUKAN":"PENGELUARAN"}</span></td><td>${rupiah(x.amount)}</td><td>—</td></tr>`).join("")}
function renderNews(){$("#newsGrid").innerHTML=DB.announcements.map(x=>`<article class="news"><div class="date">${esc(x.date)}</div><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join("");$("#nCount").textContent=DB.announcements.length}
function renderAll(){renderStudents($("#search").value);renderSchedule();renderDuty();renderTasks();renderCash();renderNews()}
function toast(x){let t=$("#toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function modal(title,html){$("#modalTitle").textContent=title;$("#form").innerHTML=html+`<button class="primary" type="submit">Simpan</button>`;$("#modal").classList.remove("hidden")}
$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target.id==="modal")$("#modal").classList.add("hidden")};
$("#search").oninput=e=>renderStudents(e.target.value);
$("#addStudent").onclick=()=>{modal("Tambah Siswa",`<label>Nama<input name="name" required></label><label>NIS<input name="nis" required></label><label>Jenis Kelamin<select name="gender"><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></label>`);$("#form").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);DB.students.push({name:f.get("name"),nis:f.get("nis"),gender:f.get("gender")});$("#modal").classList.add("hidden");renderStudents($("#search").value);$("#sCount").textContent=DB.students.length;toast("Siswa ditambahkan")}};
$("#addTask").onclick=()=>{modal("Tambah Tugas",`<label>Nama<input name="name" required></label><label>Pelajaran<input name="subject" required></label><label>Deadline<input name="due" required></label>`);$("#form").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);DB.tasks.push({id:Date.now(),name:f.get("name"),subject:f.get("subject"),due:f.get("due"),done:false});$("#modal").classList.add("hidden");renderTasks();toast("Tugas ditambahkan")}};
$("#addCash").onclick=()=>{modal("Tambah Transaksi",`<label>Keterangan<input name="description" required></label><label>Jenis<select name="type"><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select></label><label>Nominal<input name="amount" type="number" min="0" required></label>`);$("#form").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);DB.cash.push({id:Date.now(),date:new Date().toLocaleDateString("id-ID"),description:f.get("description"),type:f.get("type"),amount:+f.get("amount")});$("#modal").classList.add("hidden");renderCash();toast("Transaksi ditambahkan")}};
$("#addNews").onclick=()=>{modal("Tambah Pengumuman",`<label>Judul<input name="title" required></label><label>Isi<textarea name="body" required></textarea></label>`);$("#form").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);DB.announcements.unshift({id:Date.now(),date:new Date().toLocaleDateString("id-ID"),title:f.get("title"),body:f.get("body")});$("#modal").classList.add("hidden");renderNews();toast("Pengumuman ditambahkan")}};
$("#random").onclick=()=>{let names=DB.students.map(x=>x.name);for(let i=names.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[names[i],names[j]]=[names[j],names[i]]}Object.keys(DB.duty).forEach((d,i)=>DB.duty[d]=[names[i*2%names.length]||"Belum ada",names[(i*2+1)%names.length]||"Belum ada"]);renderDuty();toast("Piket berhasil diacak")};
load();